version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - aura-network

  # Backend FastAPI Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/app:/app/app
      - ./backend/models:/app/models
      - ./backend/services:/app/services
      - ./backend/utils:/app/utils
      - ./backend/tests:/app/tests
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    networks:
      - aura-network

  # Redis for caching and session management (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aura-network

  # PostgreSQL for data persistence (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=aura_db
      - POSTGRES_USER=aura_user
      - POSTGRES_PASSWORD=aura_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aura-network

volumes:
  redis_data:
  postgres_data:

networks:
  aura-network:
    driver: bridge 